spring.application.name=FraudAnalyzer
#Actuator
management.endpoints.web.exposure.include=health,info
# Kafka Server Configurations
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
# Kafka Producer Configurations
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.jitesh.fraudanalyzr.serdes.TransactionSerializer
# Kafka Consumer Configurations
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.jitesh.fraudanalyzr.models
app.consumer.txn.group=txn-group
app.consumer.txn.fraud.group=txn-fraud-group
# Kafka Topic Configurations
app.topics.transactions=transactions
app.topics.fraud-alerts=fraud-alerts
# Logs
logging.level.root=INFO
logging.level.com.jitesh.fraudanalyzr=DEBUG
logging.level.org.apache.kafka=INFO
# Kafka Stream Configurations
spring.kafka.streams.application-id=fraud-analyzr-stream
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=com.jitesh.fraudanalyzr.serdes.TransactionSerde
#spring.kafka.streams.state-dir=D:/Workspace/FraudAnalyzr/kafka-logs
spring.kafka.streams.properties.retention.ms=604800000
spring.kafka.streams.properties.cleanup.policy=delete
# Aivan Kafka SSL Conf for Kafka
spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.ssl.truststore.type=PEM
spring.kafka.properties.ssl.truststore.location=${KAFKA_CA_PATH:D:/Workspace/FraudAnalyzr/certs/ca.pem}
spring.kafka.properties.ssl.keystore.type=PEM
spring.kafka.properties.ssl.keystore.location=${KAFKA_KEYSTORE_PATH:D:/Workspace/FraudAnalyzr/certs/svc.pem}
spring.kafka.streams.properties.default.replication.factor=2
spring.kafka.streams.properties.replication.factor=2
spring.kafka.streams.properties.min.insync.replicas=1
spring.kafka.streams.properties.topic.retention.ms=86400000



